[project]
name = "italian_ipa"
version = "2.1.0"
description = "Anki deck with IPA symbols for phonemes and phones of the Italian language"
readme = "README.md"
requires-python = ">=3.9,<4"
authors = [
	{ name = "Simone Gaiarin", email = "simgunz@gmail.com" },
	{ name = "David Robinson" },
]
license = "CC BY-NC-SA"
dependencies = [
	"Brain-Brew>=0.3.6,<0.4.0",
]

[project.optional-dependencies]
dev = [
	"bump2version>=1.0.1,<2.0.0",
	"ffmpeg-normalize",
]
